### ISSUE TITLE
wrong selected value when use dom-repeat

### ISSUE THREAD

**Issue by duongphuhiep** [PolymerElements/iron-selector#106]
Hello,

The [#82](https://github.com/PolymerElements/iron-selector/issues/82) is closed and forgotten because the plunker example is missing.. I added one and re-open the issue:

http://plnkr.co/edit/dqSFV2XQ6x1UjJdm7fFl?p=preview

**Comment by bicknellr** [comment]
Thanks for posting this, I'll open the other issue again.
