### ISSUE TITLE
Changes to selectedValues not reflected in display

### ISSUE THREAD

**Issue by andrewmwhite** [PolymerElements/iron-selector#112]
For instance, removing an element from selectedValues does not result in it's "selected" appearance changing to deselected. See JS Bin [here](https://jsbin.com/halivox/edit?html,console,output).

The tests appear to cover cases where the selectedValues array is overwritten, not modified (pushed, shifted, spliced, etc., by the Polymer array mutation methods).

**Comment by bicknellr** [comment]
Thanks for the repro case; my first thought / hope is that this might be as simple as changing [this observer](https://github.com/PolymerElements/iron-selector/blob/8bd0853/iron-multi-selectable.html#L49) to `'_updateSelected(selectedValues.*)'`.

**Comment by HedCET** [comment]
https://github.com/ebidel/polymer-gmail/issues/12

**Comment by andrewmwhite** [comment]
Neither using 'selectedValues.*' nor 'selectedValues.splices' works, at least according to this test case: 
https://github.com/andrewmwhite/iron-selector/commit/64f80e86a63bb656e76b0e2ea8861d4d448d565c

**Comment by bicknellr** [comment]
@andrewmwhite, I talked with @cdata yesterday about this and he mentioned that `selectedValues.*` provides both the full array and the splices object at different times. Also, [it doesn't seem like your branch actually changes the observer](https://github.com/PolymerElements/iron-selector/compare/master...andrewmwhite:issue-112-test-case) - am I missing something?

**Comment by andrewmwhite** [comment]
My branch doesn't -- it just provides the test case. I tried both 'selectedValues.*' and 'selectedValues.splices' offline and neither worked.

**Comment by bicknellr** [comment]
Oh, I just noticed that your tests use the native array methods; unfortunately, [these won't trigger updates to bindings / observers / computed properties](https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-observation). Switching `s.selectedValues.arrayFn(args...)` to `s.arrayFn('selectedValues', args...)` for [these functions](https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-mutation) should help.

**Comment by andrewmwhite** [comment]
Apparently my brain was checked out yesterday -- thanks for pointing that out. I've fixed the test case and implemented your suggested change, which passes the (fixed) tests. I'll submit a PR once I verify this fixes the downstream problem I was encountering.

**Comment by bicknellr** [comment]
Awesome!
