### ISSUE TITLE
Modifying excludedLocalNames on any one element extending IronSelectableBehavior modifies it for all others

### ISSUE THREAD

**Issue by vsimonian** [PolymerElements/iron-selector#14]
To replicate:

 1. Add multiple `iron-selector`s to a page (or anything extending `IronSelectableBehavior`).
 2. Modify `excludedLocalNames` on one.
 3. Note that the `iron-selector` on which `excludedLocalNames` was modified obeys the new entries.
 4. Note that so does the other `iron-selector`.

And, voila! You have achieved quantum teleportation in Polymer.

[Here's a demonstration of the bug](http://plnkr.co/edit/U06hfTduGwb7BVxu9q3x?p=preview).

It looks like `excludedLocalNames` is pointing to the prototype instance of `excludedLocalNames`.

**Comment by ebidel** [comment]
Bump. @blasten @notwaldorf @cdata
