### ISSUE TITLE
iron-selectable (via iron-pages) fails to apply selected class

### ISSUE THREAD

**Issue by hawkett** [PolymerElements/iron-selector#16]
I'm having an issue with iron-pages whereby iron-selectable can get out of sync with the DOM - i.e. the selectedItem is one thing, while the DOM element with the 'iron-selected' class is another.

Unfortunately I have not been able to replicate the issue with a trivial test - but I do see this repeatedly in a more complicated single-page app with a lot of iron-pages components. The problem is reliably repeatable in this context - following the same flow through the application will always deliver the invalid state. Basically it looks like iron-selectable doesn't reliably apply the selected class.

Here's a screen shot example (chrome), which is the result of:

```
this.$.completionSelector.select(1);
console.log("Selected", this.$.completionSelector.selected, this.$.completionSelector.selectedItem, this.$.completionSelector.items);
console.log("Selector", this.$.completionSelector);
```

![screen shot 2015-05-18 at 11 46 04 am](https://cloud.githubusercontent.com/assets/134568/7687656/97e2bb2e-fd53-11e4-9ccb-f4f8defccfb2.png)

Item 0 was correctly selected prior to the select(1) call. Note that the iron-pages component is itself an 'iron-page', but I see this problem occurring when they're not nested.

**Comment by manifest** [comment]
The same issue. The problem occurs when the event comes from the element which are content of iron-selector (or iron-pages). It makes impossible to change the current page of 'iron-page' tapping on whatever element located inside the page.

We should remove 'activateEvent' listener from the 'iron-selector' when we are using it inside the 'iron-pages'.

```javascript
    ready: function() {
      var p = this.$.pages;
      p._removeListener(p.activateEvent);
    }
```

Full example:
```javascript
<link rel='import' href='../polymer/polymer.html'>
<link rel='import' href='../iron-pages/iron-pages.html'>
    
<dom-module id='ex-app'>
  <template>

    <iron-pages id='pages' selected='0'>
      <section>
        <h1>Page 0</h1>
        <button on-tap='onInnerTap'>inner button</button>
      </section>
      <section>
        <h1>Page 1</h1>
        <button on-tap='onInnerTap'>inner button</button>
      </section>
      <section>
        <h1>Page 2</h1>
        <button on-tap='onInnerTap'>inner button</button>
      </section>
    </iron-pages>
    <button on-tap='onOuterTap'>outer button</button>
  
  </template>
</dom-module>

<script>

  Polymer({
  
    is: 'ex-app',

    ready: function() {
      var p = this.$.pages;
      p._removeListener(p.activateEvent);
    },

    onInnerTap: function() {
      this.$.pages.selected = '1';
      console.log(['inner tap', this.$.pages.selected]);
    },

    onOuterTap: function() {
      this.$.pages.selected = '2';
      console.log(['puter tap', this.$.pages.selected]);
    }
  
  });
</script>
```

```javascript
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
    <meta name='viewport' content='width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes'>
        
    <title>Ex</title>
      
    <script src="webcomponentsjs/webcomponents-lite.min.js"></script>
    <link rel='import' href='elements/ex-app.html'>
    <style>
      html,body {
        height: 100vh;
        margin: 0;
        background-color: #e5e5e5;
      }
    </style>
  </head>
  <body>
  
    <ex-app></ex-app>

  </body>
</html>
```

**Comment by hawkett** [comment]
[jsbin example](http://jsbin.com/gacolo/5/edit?html,output) of the problem (thanks @manifest)

**Comment by hawkett** [comment]
Further digging into this problem, @manifest is describing a different issue - just with very similar effects. 

[jsbin demonstrating _this_ issue] (http://jsbin.com/besoku/28/edit)

There's a bunch of things going on here, but essentially there's a race condition that will prevent a call to ```select()``` from actually triggering the complex observer on the state change. 

The problem occurs in two parts - highlighted in the jsbin comments. 

1 - Trying to call ```select()``` before the iron-pages component is finished initialising results in an invalid state - properties have not yet been initialised, and the complex observer ```_updateSelected(attrForSelected, selected)``` in ```iron-selectable``` needs ```attrForSelected``` to have been set. The following debug view helps understand why - when we run through the args to the observer ```attrForSelected``` is undefined, which returns immediately when there's more than 1 argument. Not returning args means we never call _updateSelected(): [code ref](https://github.com/Polymer/polymer/blob/cd4acffab214fb407aec5c10092c8b3b62015bdb/src/lib/bind/effects.html#L64)

![screen shot 2015-06-05 at 5 38 42 pm](https://cloud.githubusercontent.com/assets/134568/8017421/24b4fb66-0baa-11e5-8b56-1d04ce585fb7.png)

2 - Nothing will be actioned when we subsequently call select() if we don't actually change the value: [code ref](https://github.com/Polymer/polymer/blob/cd4acffab214fb407aec5c10092c8b3b62015bdb/src/lib/bind/accessors.html#L51) - therefore subsequent attempts to select the same page will also fail.

I can see a whole bunch of ways this might be resolved, but maybe a first step is to make sure the 'old' value is not set if the component is in an invalid state. At least subsequent calls to set the value when the component becomes initialised will succeed.

Perhaps the answer is for the developer to be responsible for avoiding these races, but I can see them being a nightmare to debug and weed out in complex applications.

Note: I've deleted my previous comment that contained an incorrect jsbin - it's still available in https://github.com/PolymerElements/iron-pages/issues/3

**Comment by hawkett** [comment]
Thinking on this some more, I can see that the approach used in the jsbin above is considered an anti-pattern, and that [this jsbin](http://jsbin.com/doxuno/2/edit?html,console,output) is a far better way to approach this trivial case. That said, there's definitely been discussion polymer slack about difficulties reasoning about code with undefined properties, so there might still be something here.

Independent of that, I think there's still a problem lurking here - namely that **polymer considers setting an attribute to be idempotent** [code ref](https://github.com/Polymer/polymer/blob/cd4acffab214fb407aec5c10092c8b3b62015bdb/src/lib/bind/accessors.html#L51), however the first jsbin shows that this is not the case. It's easy to see when undefined values break idempotence from the image in the previous post, and it seems we should avoid changing the 'old' value when this occurs. Still not idempotemt, but at least subsequent attempts may succeed.

This discussion is no longer about iron-selector - going to close this issue and link to it from something over at Polymer/polymer.
