### ISSUE TITLE
OnDetach removing event listener, but OnAttach isn't adding it back

### ISSUE THREAD

**Issue by albinrangefelt** [PolymerElements/iron-selector#24]
In the "detached" function the activate-event-listener (usually "on-click") is removed, but it's not put back by the "attached" function. For me  this caused the <paper-tabs> element to stop working (for unrelated reasons it was getting detached and then reattached, and after that clicking on tabs would not select them anymore, though the "ripple" animation still triggered). Checking in the Chrome dev console I could see that the onClick event was missing from the tab items. 
Patching the attached function so the activate-event-listener is put back fixed the issue for me.

**Comment by ronnyroeller** [comment]
+1

**Comment by notwaldorf** [comment]
Already fixed in #64
