### ISSUE TITLE
Possible bug in the definition of "selectable" property?

### ISSUE THREAD

**Issue by Claudio-DC** [PolymerElements/iron-selector#25]
In "iron-selectable.html" the "selectable" property is defined as follows:

selectable: String,

Should it not be ?

selectable: { type: String },

**Comment by wilbiga** [comment]
i had the same problem and  selectable: { type: String } was not enough. So i had to add the value: null to start working properly.

**Comment by notwaldorf** [comment]
I think this is allowed syntax. :)
