### ISSUE TITLE
selectedItem goes to undefined and then to new value

### ISSUE THREAD

**Issue by jklein24** [PolymerElements/iron-selector#27]
Let me know if this is expected, but it makes it hard to keep track of the previously selected item.

I have a structure sort of like this:

<div id="mainContainer">
      <page-header selected-page="[[selectedPage]]">
      <page-header>
        <iron-pages id="pageContainer" selected-item="{{selectedPage}}">
           .....
        </iron-pages>
</div>

What the page-header shows depends a bit on the previously selected item. Inside page-header, there's an observer on selectedPage. The issue I'm seeing is that the observer is triggered with selectedPage equal to undefined before selecting the new value. This messes up our ability to track the transition. Here's the real code:

https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/resources/settings/settings_main/settings_main.html

https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/resources/settings/settings_page/settings_page_header.js

**Comment by jklein24** [comment]
Would it make sense to wrap this line in an "if (isSelected) { .. }"?

**Comment by morethanreal** [comment]
@jklein24 Hmm, I think that logic is needed so you can clear the selection by doing `this.selected = null`.

**Comment by jklein24** [comment]
Yeah, I was worried that might be the case :-/. Any other way to get the behavior I'm looking for? I know this wasn't the case in 0.5

**Comment by morethanreal** [comment]
I observe `selected` in https://github.com/PolymerElements/neon-animation/blob/master/neon-animated-pages.html#L94. Does that work for you?

**Comment by notwaldorf** [comment]
We can't repro this anymore (here's the jsbin we tried: http://output.jsbin.com/hihufuf/1) but please re-open this if it's still happening!
