### ISSUE TITLE
Children added to <iron-selector> before it is added to document not marked selected

### ISSUE THREAD

**Issue by shaydon** [PolymerElements/iron-selector#30]
If I programatically construct an `<iron-selector>` element like this ([jsbin, slow to load](http://jsbin.com/qajela/2/edit?html,output)):
```javascript
    var parent = document.createElement('iron-selector');
    parent.selected = "0";
    
    var child = document.createElement('div');
    child.innerHTML = 'Item 0';
    
    Polymer.dom(parent).appendChild(child);
    document.body.appendChild(parent);
```
then the child `<div>` does not receive the `iron-selected` class I hoped for (using Chrome). Possibly this is considered unsupported as I set the `selected` property before appending the corresponding child; but if I simply reverse the final two lines - adding parent to document before adding child to parent - the class is set correctly ([jsbin](http://jsbin.com/qajela/1/edit?html,output)).

It looks like the inconsistency is due to [iron-selectable.html](https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html) only setting up its `MutationObservers` during the `attach()` callback. Naively it might be fixed by either calling `_updateSelected()` directly during `attach()` ([diff](https://github.com/PolymerElements/iron-selector/compare/master...shaydon:update-on-attach)) or by setting up the observers during `ready()` ([diff](https://github.com/PolymerElements/iron-selector/compare/master...shaydon:observe-earlier)), though I don't know enough about Polymer to know if either of these would be problematic.

My reason for wanting the quoted code to work is simply that I'm exploring using Polymer elements with a library (https://github.com/Matt-Esch/virtual-dom) that happens to construct elements in the order element -> properties -> children. All else being equal it does seem desirable that an element's state be a pure function of its public properties.

**Comment by morethanreal** [comment]
It seems reasonable to call `_updateSelected()` on attach, since the element's children might have changed between `ready()` and `attached()`.

**Comment by nick211** [comment]
I'm suspecting the same problem occurs when using a dom-repeat to dynamically change the set of selectable elements, e.g.:

    <template>
      <iron-selector multi selected-values="[[sel]]" attr-for-selected="value"
                     selectable="paper-checkbox" selected-attribute="checked">
        <template is="dom-repeat" items="[[vals]]" as="v">
          <paper-checkbox value="[[v]]">[[v]]</paper-checkbox>
        </template>
      </iron-selector>
    </template>

    ....
    
    ready: function() {
      this.vals = ["a", "b"];
      this.sel = ["a"];
    }

Expected behavior: checkbox "a" is selected.
Actual behavior: no checkboxes are selected.

Seems like Polymer updates the iron-selector first, then creates the repeated paper-checkboxes, and does not update the selection state after the checkboxes have been added.

**Comment by Trakkasure** [comment]
2 things you need to do to work around this issue:
first: use ``` value$="[[v]]" ``` in the paper-checkbox element.
second, in ready() add: ```setTimeout(function(){this.querySelector('iron-selector')._updateSelected()}.bind(this));```

**Comment by Trakkasure** [comment]
I've added some code that makes this behave as expected... This is all related to #33 #43 and #44

**Comment by davidrissato** [comment]
As a workaround, I needed to work this way:

    <template>
        ...
                <paper-tabs selected="{{selectedindex}}">
                    <template is="dom-repeat" items="[[items]]">
                        <paper-tab>[[item.name]]</paper-tab>
                    </template>
                </paper-tabs>
       ...
    </template>
    ...
    <script>
        Polymer({
            is: "app-header-menu",
            /*...*/
            attached: function() {
                var el = this.$$('paper-tabs');
                el._updateSelected();
                var that = this;
                el.addEventListener("iron-select", that._onTabSelected.bind(that) );
            },
            properties: {
                selectedindex: {
                    type: String,
                    notify: true,
                    readOnly: false,
                    reflectToAttribute: true
                }
            }

 Do you see a better way?
