### ISSUE TITLE
Bindings to `selectedItems` do not notify interested parties

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-selector#33]
repo: http://jsbin.com/guniqopiwi/1/edit

For example, `_computeTitle()` only gets called after the first selection is made. Subsequent taps on items do not call it:

```
<template id="t" is="dom-bind">
  <iron-selector multi
                 selected-attribute="selected"
                 selected-items="{{selectedThreads}}">
    <template is="dom-repeat" items="[[threads]]">
      <div>{{item.name}}</div>
    </template>
  </iron-selector>
  How many selected: <span>{{_computeTitle(selectedThreads.length)}}</span>
</template>
```

**Comment by jongeho1** [comment]
+1 same issue for ```selected-values``` attribute. I bound to ```on-iron-select``` and ```on-iron-deselect``` and notified the path in the containing element as a workaround. ```on-selected-values-changed``` does not seem to work for individual item changes.
