### ISSUE TITLE
`excludedLocalNames` should be private

### ISSUE THREAD

**Issue by sjmiles** [PolymerElements/iron-selector#40]

**Comment by blasten** [comment]
friendly ping.

**Comment by czwiryk** [comment]
May I ask why this change was made? I found this immensely useful when rolling my own autocomplete widget. Is there an alternative way to exclude elements from selection?

**Comment by sjmiles** [comment]
The intent was always that one opts-in to nodes via `selectable` (instead of opting-out with `excludedLocalNames`).

`excludedLocalNames` is part of the internal implementation of selectable and was not supposed to be exposed for configuration. It would require extra code to extend that contract.

It may be that `iron-selectable` needs an opt-out complement to `selectable`, feel free to make a feature request (and I suggest it makes most sense as a selector, not a list of tag-name exclusions).

**Comment by czwiryk** [comment]
I must have missed `selectable`, that works perfectly. Thanks for following up!
