### ISSUE TITLE
multi selection's on-selected-values-changed will not invoked when it changes

### ISSUE THREAD

**Issue by jwu** [PolymerElements/iron-selector#44]
I found the source will assigned array directly: 

 - https://github.com/PolymerElements/iron-selector/blob/master/iron-multi-selectable.html#L106
 - https://github.com/PolymerElements/iron-selector/blob/master/iron-multi-selectable.html#L108

and I think use Polymer's array operation: `this.push('selectedValues', value)`, `this.splice('selectedValues', i, 1)` will solve this problem.

**Comment by pe4enushkin** [comment]
+1
Because of this problem, binding to selectedValuse also not populate data into my element.

**Comment by oddg** [comment]
The fix allows proper data population to the binded properties. But it [seems to me](http://stackoverflow.com/questions/31604153/polymer-observing-property-change-for-an-array-with-data-binding) that observing change on this binded property is still an issue.

**Comment by leogr** [comment]
:+1:
I encountered the same problem. Using Polymer's array operation worked fine in my case.
