### ISSUE TITLE
IronMultiSelectableBehavior: no _updateSelected() on DOM mutation

### ISSUE THREAD

**Issue by sklobovskaya** [PolymerElements/iron-selector#69]
IronMultiSelectableBehavior fails to update the selection (`this._updateSelected()`) when the DOM is mutated.

IronSelectableBehavior calls `this._updateSelected()` on DOM mutation, here:

https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html#L295

However, when using IronMultiSelectableBehavior, the above line is never executed because IronMultiSelectableBehavior uses `this.selectedValues` instead, and thus `this.selected` is always null.

**Comment by eliseosoto** [comment]
The problem appears to be in IronSelectableBehavior._observeContent

https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html#L277

`var content = node.querySelector('content');`
`content` is null

And then after an element that has IronSelectableBehavior is attached the `_contentObserver` is undefined.
