### ISSUE TITLE
iron-selector 1.0.8 doesn't work with more-routing

### ISSUE THREAD

**Issue by nloewen** [PolymerElements/iron-selector#83]
After updating iron-selector to 1.0.8, it no longer works with more-routing.

See: https://github.com/PolymerLabs/more-routing/issues/77

**Comment by sgoryachkin** [comment]
I believe that it is more-routing problem, 
but iron-selector.items is not changed de facto during "iron-items-changed" event fired because the event is fired before this._updateItems() in _observeI

**Comment by bicknellr** [comment]
Thanks for filing this, I'm going to close it as a dup of #89, even though this came first, since the other has more description.
