### ISSUE TITLE
inconsistent type of selected property

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/iron-selector#84]
Repro: http://jsfiddle.net/dmw9fgf9/ (see console)

```
<paper-menu attr-for-selected="data-value">
    <paper-item data-value$="[[val0]]"></paper-item>
    <paper-item data-value$="[[val1]]"></paper-item>
</paper-menu>
```

`paper-menu`'s `selected` property is supposed to be type String. What happens when the data-values are Numbers?

I would expect `selected` to still be a String, especially because `data-value$=` should bind to the *attribute*, which is always of type String.

But if val0 and val1 are both Number properties, and val0 is set to 0 and val1 is 1, then `selected` is a `String` when the first item is selected, but a `Number` when the second item is selected.

**Comment by bicknellr** [comment]
Looks like #102 is going to fix this: [before](http://jsbin.com/zebuxo/edit?html,console,output), [after](http://jsbin.com/xazahi/1/edit?html,console,output). Note the selected branch in the polygit base href.

**Comment by arthurevans** [comment]
Works in master now, closing.
