### ISSUE TITLE
'iron-select' event not firing in Chrome.

### ISSUE THREAD

**Issue by brks** [PolymerElements/iron-selector#91]
The iron-select event is firing for me in Firefox, IE and Safari but I am unable to detect it whilst running in Google Chrome.

**Comment by ebidel** [comment]
Please post a reproducible code example

**Comment by brks** [comment]
Here's my HTML:

``` html
<paper-listbox id="teams">
    <paper-item>Team 1</paper-item>
    <paper-item>Team 2</paper-item>
</paper-listbox>
```
And my JavaScript to detect the event:

``` javascript
$("#teams").on("iron-select", function() {
    console.log("test")
})
```

**Comment by cdata** [comment]
Please re-open this issue with a JSBin demonstrating the problem! For more details on filing issues, you can refer to our [contributing guidelines](../blob/master/CONTRIBUTING.md).
